#---------- BasicCommands Config File ----------
#The original author is Thromax, if you have downloaded this plugin from another author you should remove it and download the original or your server
#could be in danger
#El autor original de este plugin es Thromax, si has descargado este plugin de otro autor deberias eliminarlo y descargarlo de su autor oficial o tu
#servidor podria estar comprometido

#Remember that you can use colors by this codes:
#Recuerda que puedes usar los colores con estos codigos:
# §0 BLACK/NEGRO                                          §A GREEN/VERDE                §O ITALIC/INCLINADA
# §1 DARK BLUE/AZUL OSCURO                                §B AQUA/AGUAMARINA
# §2 DARK GREEN/VERDE OSCURO                              §C RED/ROJO
# §3 DARK AQUA/AGUAMARINA OSCURO                          §D PINK/ROSA
# §4 DARK RED/ROJO OSCURO                                 §E YELLOW/AMARILLO
# §5 DARK PURPLE/VIOLETA OSCURO                           §F WHITE/BLANCO
# §6 GOLD(Orange)/DORADO(Naranja)                         §M STRIKE THROUGH/TACHADO
# §7 GRAY/GRIS                                            §N UNDERLINED/SUBRAYADO
# §8 DARK GRAY/GRIS OSCURO                                §L BOLD/NEGRITA
# §9 BLUE/AZUL                                            §K RANDOM/ALEATORIO
Configs:
    #Number of times that your user will be able to use /back before they dead again, you have to disallow bc.back.inf to get it working (0 or less=infinite)
    #Numero de veces que tus usuarios podran usar /back antes de su siguiente muerte, tienes que quitar el permiso bc.back.inf para que funcione (0 o menos=infinito)
    BackUses: 0
    
Messages:
    System:
        #Load Message
        #This is the message that will be shown in the console when the plugin loads
        #Este es el mensaje que se mostrara por consola cuando se cargue el plugin
        Load: "§1Se ha cargado el plugin"

        #Start Message
        #This is the message that will be shown in the console when the plugin starts
        #Este es el mensaje que se mostrara por consola cuando se inicie el plugin
        Start: "§1Se ha iniciado el plugin"
        
        #Disable Message
        #This is the message that will be shown in the console when the plugin stops
        #Este es el mensaje que se mostrara por consola cuando se finalice el plugin
        Disable: "§1El plugin ha sido finalizado"
        
        #Saving Message
        #This is the message that will be shown in the console when the plugin saves the progress of the server
        #Este es el mensaje que se mostrara por consola cuando le plugin guarde el progreso del servidor
        Saving: "§6Guardando el servidor..."
        
        #Stopping Message
        #This is the message that will be shown globally when the plugin stops the server
        #Este es el mensaje que se mostrara globalmente cuando le plugin detenga servidor
        Stopping: "§6Deteniendo el servidor..."

    #Welcome Message
    #This is the message that your users are going to receive every time they join to the server.
    #Este es el mensaje que tus usuarios recibiran cada vez que entren en el servidor.
    Welcome: "§6Bienvenid@ al servidor"
    
    #Teleported Message
    #This is the message that your users are going to receive every time they succesfully gets teleported
    #Este es el mensaje que tus usuarios recibiran cada vez que se teletransporten con exito
    Teleported: "§6Pium!! shawn!! wuaaank!! Te has §3teletransportado§6!!"
    
    #New Death Location Message
    #This is the message that your users are going to receive every time they dead
    #Este es el mensaje que tus usuarios recibiran cada vez que mueran
    NewDeathLocation: "§6Para volver a tu punto de muerte usa §3/back"
    
    GameModes:
        
        #GameMode Change Message
        #This is the message that your users are going to reveive every time they changes its GameMode
        #Este es el mensaje que recibiran tus usuarios cada vez que cambien de GameMode
        
        Survival: "§6Has cambiado al modo §3survival"
        
        Creative: "§6Has cambiado al modo §3creativo"
        
        Adventure: "§6Has cambiado al modo §3aventura"
        
        Spectator: "§6Has cambiado al modo §3espectador"
    
Alerts:
    #No Permission Message
    #This is the message that will be shown to a player when it has not permissions to perform that command
    #Este es el mensaje que se le mostrara al jugador cuando no tenga permisos para usar un comando
    Permission: "§CNo tienes permisos para usar este comando"
    
    #Too Many Arguments Message
    #This is the message that will be shown to a player when enters too many arguments on a command
    #Este es el mensaje que se le mostrara a un jugador cuando introduzca demasiados argumentos en un comando
    TooManyArgs: "§CDemasiados argumentos!!"
    
    #Too Many Backs Message
    #This is the message that will be shown to a player when enters the command /back more times than the limit (Only if BackUses config is higher than 0)
    #Este es el mensaje que se le mostrara a un jugador cuando introduzca el comando /back mas veces que el limite (Solo si la configuracion BackUses es mayor de 0)
    TooManyBacks: "§CDemasiados usos, volveras a poder usarlo tras revivir"
    
    #No Move-Permission Message
    #This is the message that will be shown to a player when it has not permissions to move
    #Este es el mensaje que se le mostrara al jugador cuando no tenga permisos para moverse
    Movement: "§CNo tienes permisos para moverte"
    
    #Not a Player
    #This is the message that will be shown to an entity when it tries to use an "players-only" command
    #Este es el mensaje que se le mostrara a una entidad cuando intente utilizar un comando "solo para jugadores
    NotPlayer: "§CEste comando solo puede ser utilizado por un jugador"

    #There is Not Last Death Localization Message
    #This is the message that will be shown to a player when it has not last death localization (Using the /back command)
    #Este es el mensaje que se le mostrara a un jugador cuando no tenga una ubicacion de ultima muerte (Con el comando /back)
    NoLastDeath: "§CNo ninguna ubicacion de ultima muerte"
    
    #Insert A Valid Game Mode Message
    #This is the message that will be shown to a player when enters an incomplete GameMode-Command
    #Este es el mensaje que se le mostrara a un jugador cuando introduzca un comando incompleto de GameMode
    InsValidGM: "§CInserta un modo de juego valido"
    
    #Insert A Valid Player Message
    #This is the message that will be shown to a player when enters an incomplete command that needs an username
    #Este es el mensaje que se le mostrara a un jugador cuando introduzca un comando incompleto que requiere de un nombre de jugador
    InsValidPlayer: "§CInserta un jugador valido"
    
    

Healing and Feeding:
    #Self Healed Message
    #This is the message that will be shown to a player when it gets healed by itself (Using /heal)
    #Este es el mensaje que se le mostrara a un jugador cuando se cure a si mismo (Con /heal)
    SelfHealed: "§6Has sido curado!!"
    
    #Healed By The Console Message
    #This is the message that will be shown to a player when it gets healed by the console
    #Este es el mensaje que se le mostrara a un jugador cuando sea curado por la consola
    HealedByConsole: "§6La consola te ha curado!!"
    
    #Self Feeded Message
    #This is the message that will be shown to a player when it gets feeded by itself (Using /feed)
    #Este es el mensaje que se le mostrara a un jugador cuando se alimente a si mismo (Con /feed)
    SelfFeeded: "§6Has sido alimentado!!"
    
        #Feeded By The Console Message
    #This is the message that will be shown to a player when it gets feeded by the console
    #Este es el mensaje que se le mostrara a un jugador cuando sea alimentado por la consola
    FeededByConsole: "§6La consola te ha alimentado!!"

#---------------------------------------------------------------------------------------------------------------------------------------------------
#DO NOT EDIT THIS!!
#NO EDITES ESTO!!
version: 1.0