name: BasicCommands
author: Thromax
version: 1.0
main: com.thromax.basiccommands.Main
description: A bunch of short commands to make your Bukkit/Spigot experience much easier/Un puñado de cortos comandos para hacer de tu experiencia Bukkit/Spigot mucho más sencilla
commands:

        
    exit:
        description: Saves all changes and stops the server/Guarda todos los cambios y detiene el servidor
        usage: /exit
        
    save:
        description: Saves all changes/Guarda todos los cambios
        usage: /save
        
    heal:
        description: Heals a player/Cura a un jugador
        usage: /heal [player]
        
    feed:
        description: Feeds a player/Alimenta a un jugador
        usage: /feed [player]
        
    gm:
        description: Changes gamemode of a player/Cambia el gamemode de un jugador
        usage: /gm (gamemode or 1-3) [player]
        
    dawn:
        description: Changes time to dawn on the current world/Cambia el tiempo al amanecer en el mundo actual
        usage: /dawn
    day:
        description: Changes time to day on the current world/Cambia el tiempo a dia en el mundo actual
        usage: /day
        
    dusk:
        description: Changes time to dusk on the current world/Cambia el tiempo al atardecer en el mundo actual
        usage: /dusk
        
    night:
        description: Changes time to night on the current world/Cambia el tiempo a noche en el mundo actual
        usage: /night
        
    version:
        description: Displays version info/Muestra informacion de la version
        usage: /version
        
    back:
        description: Teleports you to your last death localization/Te teletransporta a tu ultima ubicacion de muerte
        usage: /back
        
    invedit:
        description: Displays a player's inventory to edit it / Muestra el inventario de un jugador para editarlo
        usage: /invedit [player]
